### PR TITLE
Update to tree-sitter to 0.19.2

### LINKED ISSUE #10: Update to support tree-sitter 0.19.3
Hey @cstrahan, hope you doing great. I was trying to use tree-sitter-nix but didn't work, I think its due to version miss-match. It would be awesome if it gets update. Thanks

### PR DESCRIPTION
**Pull request by tami5**
closes #10 

NOTE: I'm not confident in the way I went about to update tree-sitter. I basically did
manually updated package.json, parser.c and tree-sitter/parser.h.

Thanks

### CODE REVIEW

**Comment by milahu** [comment]
push @cstrahan

**Comment by cstrahan** [comment]
Thanks for the nudge -- lost track of this. I'll see if I can get this updated today.

**Comment by cstrahan** [comment]
There are a couple tweaks needed (e.g. the cargo repository should point here, and need to uncomment the stuff for the `scanner.c`), but I'll do that in a follow up commit. Thanks!

**Comment by milahu** [comment]
> There are a couple tweaks needed

* package.json: update version (currently still 0.0.1)

**Pull request merged**
