### PR TITLE
add git metadata and examples to be run

### PR DESCRIPTION
**Pull request by justinwoo**

### CODE REVIEW

**Comment by cstrahan** [comment]
Hi @justinwoo! Thanks for contributing.

So, I was unaware of the `linguist-vendored` gitattributes and had to look up how they work / what they do. It sounds like that will direct GH to treat the attributed files as vendored/external code, and thus will not count towards the stats. Considering that I personally wrote `src/scanner.cc`, perhaps that should be an exception? Maybe something like:

```gitattributes
/src/** linguist-vendored
/src/scanner.cc linguist-vendored=false
/examples/* linguist-vendored
```

Still reviewing other bits of your PR.

**Comment by cstrahan** [comment]
Was the rationale behind parsing those examples something along the lines of a sanity check to make sure the scanner doesn't segfault / loop forever? Otherwise, I would think leveraging the test corpus would be more useful than dumping those ASTs on each test run. Perhaps we could have the best of both worlds by creating a `corpus/build.txt` and `corpus/fetch-github.txt` and writing a complete test for those (though, if the shape of the grammar changes, that might be tedious -- probably still worthwhile, I suspect).

The `.gitattributes` and `.gitignore` changes are certainly solid, though :+1:.

**Comment by cstrahan** [comment]
I've applied the git metadata portion of your PR. Lemme know what you think of my questions regarding `examples/*` and we can tackle that in a follow PR. Thanks!

**Comment by justinwoo** [comment]
Yes, I want to mostly see that the examples do parse and what their output is, but not track the minute changes to the output in corpus. Similar to what tree-sitter-javascript and other projects do

**Pull request closed without merging**
